$(FINAL_MEMDIN_PDF): $(MEMDIN_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(MEMDIN_BASE) $(MEMDIN_BASE)/slides.tex

$(FINAL_MEMDIN_EJ_PDF):	$(MEMDIN_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(MEMDIN_BASE)-ej $(MEMDIN_BASE)/hoja-ej.tex

