$(FINAL_INTROCPP_PDF): $(INTROCPP_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(INTROCPP_BASE) $(INTROCPP_BASE)/slides.tex

$(FINAL_INTROCPP_EJ_PDF):	$(INTROCPP_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(INTROCPP_BASE)-ej $(INTROCPP_BASE)/ej/hoja-ej.tex
