$(FINAL_OPERADORES_PDF): $(OPERADORES_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(OPERADORES_BASE) $(OPERADORES_BASE)/slides.tex

$(FINAL_OPERADORES_EJ_PDF):	$(OPERADORES_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(OPERADORES_BASE)-ej $(OPERADORES_BASE)/ej/hoja-ej.tex

