$(FINAL_CONTROL_PDF): $(CONTROL_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(CONTROL_BASE) $(CONTROL_BASE)/slides.tex

$(FINAL_CONTROL_EJ_PDF):	$(CONTROL_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(CONTROL_BASE)-ej $(CONTROL_BASE)/ej/hoja-ej.tex
