$(FINAL_ERRORES_PDF): $(ERRORES_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(ERRORES_BASE) $(ERRORES_BASE)/slides.tex

$(FINAL_ERRORES_EJ_PDF):	$(ERRORES_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(ERRORES_BASE)-ej $(ERRORES_BASE)/ej/hoja-ej.tex

