ERRORES_BASE= 06-errores
ERRORES_PARTS= \
$(ERRORES_BASE)/*.tex  \
metadata.tex \
license-cc.tex \
ejemplos/$(ERRORES_BASE)/enlace/*cpp \
ejemplos/$(ERRORES_BASE)/prepost/*.cpp

ERRORES_PDF=$(ERRORES_BASE).pdf

FINAL_ERRORES_PDF=$(FINAL_DIR)/$(ERRORES_PDF)
