CLASES_BASE=09-clases
CLASES_PARTS= \
$(CLASES_BASE)/*.tex  \
ejemplos/$(CLASES_BASE)/fecha-flibres/* \
ejemplos/$(CLASES_BASE)/fecha2/* \
ejemplos/$(CLASES_BASE)/fecha3/* \
ejemplos/$(CLASES_BASE)/fecha4/* \
metadata.tex

CLASES_PDF=$(CLASES_BASE).pdf

FINAL_CLASES_PDF=$(FINAL_DIR)/$(CLASES_PDF)
