CLASES_BASE=09-clases
CLASES_PARTS= \
$(CLASES_BASE)/*.tex  \
ejemplos/$(CLASES_BASE)/fecha-flibres/* \
ejemplos/$(CLASES_BASE)/fecha-fmiembro/* \
ejemplos/$(CLASES_BASE)/fecha-clase/* \
ejemplos/$(CLASES_BASE)/fecha-ctor/* \
metadata.tex \
license-cc.tex

CLASES_PDF=$(CLASES_BASE).pdf

FINAL_CLASES_PDF=$(FINAL_DIR)/$(CLASES_PDF)

CLASES_EJ_PARTS=$(CLASES_BASE)/hoja-ej.tex
CLASES_EJ_PDF=$(CLASES_BASE)-ej.pdf
FINAL_CLASES_EJ_PDF=$(FINAL_DIR)/$(CLASES_EJ_PDF)

