all: test1 test2 test3

test1:	main1.cpp
	g++ main1.cpp -o test1 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

test2:	main2.cpp
	g++ main2.cpp -o test2 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

test3:	main3.cpp
	g++ main3.cpp -o test3 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra
