HOLA_BASE= 02-hola
HOLA_PARTS= \
$(HOLA_BASE)/*.tex  \
metadata.tex \
license-cc.tex

HOLA_PDF=$(HOLA_BASE).pdf

FINAL_HOLA_PDF=$(FINAL_DIR)/$(HOLA_PDF)

HOLA_EJ_PARTS=$(HOLA_BASE)/hoja-ej.tex
HOLA_EJ_PDF=$(HOLA_BASE)-ej.pdf
FINAL_HOLA_EJ_PDF=$(FINAL_DIR)/$(HOLA_EJ_PDF)

