$(FINAL_IOSTREAM_PDF): $(IOSTREAM_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(IOSTREAM_BASE) $(IOSTREAM_BASE)/slides.tex

$(FINAL_IOSTREAM_EJ_PDF):	$(IOSTREAM_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(IOSTREAM_BASE)-ej $(IOSTREAM_BASE)/hoja-ej.tex

