IOSTREAM_BASE= 13-iostream
IOSTREAM_PARTS= \
$(IOSTREAM_BASE)/*.tex  \
ejemplos/$(IOSTREAM_BASE)/filtro/* \
ejemplos/$(IOSTREAM_BASE)/ruta/* \
ejemplos/$(IOSTREAM_BASE)/error/* \
ejemplos/$(IOSTREAM_BASE)/except/* \
ejemplos/$(IOSTREAM_BASE)/calendario/* \
metadata.tex \
license-cc.tex

IOSTREAM_PDF=$(IOSTREAM_BASE).pdf

FINAL_IOSTREAM_PDF=$(FINAL_DIR)/$(IOSTREAM_PDF)

IOSTREAM_EJ_PARTS=$(IOSTREAM_BASE)/hoja-ej.tex
IOSTREAM_EJ_PDF=$(IOSTREAM_BASE)-ej.pdf
FINAL_IOSTREAM_EJ_PDF=$(FINAL_DIR)/$(IOSTREAM_EJ_PDF)

