IOSTREAM_BASE= 13-iostream
IOSTREAM_PARTS= \
$(IOSTREAM_BASE)/*.tex  \
ejemplos/$(IOSTREAM_BASE)/filtro/* \
ejemplos/$(IOSTREAM_BASE)/ruta/* \
ejemplos/$(IOSTREAM_BASE)/error/* \
ejemplos/$(IOSTREAM_BASE)/except/* \
metadata.tex

IOSTREAM_PDF=$(IOSTREAM_BASE).pdf

FINAL_IOSTREAM_PDF=$(FINAL_DIR)/$(IOSTREAM_PDF)
