$(FINAL_FUNCIONES_PDF): $(FUNCIONES_PARTS) $(CONFIG_INPUT) $(IMG_INPUT)
	$(LATEXMK) -jobname=$(FUNCIONES_BASE) $(FUNCIONES_BASE)/slides.tex

$(FINAL_FUNCIONES_EJ_PDF):	$(FUNCIONES_EJ_PARTS) $(CONFIG_INPUT)
	$(LATEXMK) -jobname=$(FUNCIONES_BASE)-ej $(FUNCIONES_BASE)/hoja-ej.tex

