all: vec1 vec2 vec3 notas unique

vec1:	vec1.cpp
	g++ vec1.cpp -o vec1 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

vec2:	vec2.cpp
	g++ vec2.cpp -o vec2 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

vec3:	vec3.cpp
	g++ vec3.cpp -o vec3 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

notas:	notas.cpp
	g++ notas.cpp -o notas -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

unique:	unique.cpp
	g++ unique.cpp -o unique -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

