all: check nocheck

check:	check.cpp
	g++ check.cpp -o check -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

nocheck: nocheck.cpp
	g++ nocheck.cpp -o nocheck -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra
