all: test1 test2

test2:	main2.cpp
	g++ main2.cpp -o bin/test2 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra

test1:	main1.cpp
	g++ main1.cpp -o bin/test1 -std=c++11 -Wall -Weffc++ -Werror -Wpedantic -Wextra
